### ISSUE TITLE
Cannot install due to Cloudflare SSL issue

### ISSUE THREAD

**Issue by jf647** [joshuarubin/zb#12]
Attempting to install gives this error:

package jrubin.io/zb: unrecognized import path "jrubin.io/zb" (parse https://jrubin.io/zb?go-get=1: no go-import meta tags ()

Trying to fetch that URL manually (or just visit jrubin.io in a browser) gives a 526 error (a code that seems to be Cloudflare specific) indicating that the origin site SSL cert is invalid.

**Comment by joshuarubin** [comment]
New letsencrypt cert was automatically installed, but haproxy didn't pick it up on a soft restart. Will have to see why that happened, but it's working now. Thanks for the report!
